### ISSUE TITLE
Can't find VPP Agent's Configuration OpenAPI definitions.

### ISSUE THREAD

**Issue by lxyscls** [ligato/docs#110]
Hello, guys. Where are the definitions? I can't find them on the [swaggerhub](https://app.swaggerhub.com/search?owner=chrisM9).

**Comment by chrismetz09** [comment]
OpenAPI definitions for VPP agent configuration do not exist at this time. Look over:
https://github.com/ligato/vpp-agent/pull/1787
https://docs.ligato.io/en/latest/api/api-vpp-agent/#configuration
https://docs.ligato.io/en/latest/user-guide/agentctl/#config
