### ISSUE TITLE
add kvscheduler diagram to plugin/kvscheduler

### ISSUE THREAD

**Issue by chrismetz09** [ligato/docs#17]
diagram at https://github.com/ligato/vpp-agent/blob/master/docs/kvscheduler/kvscheduler.md improves understanding

**Comment by ondrej-fabry** [comment]
This is actually already in the docs: https://docs.ligato.io/en/latest/developer-guide/kvscheduler/#diagram

However we should probably add some links in there..

**Comment by chrismetz09** [comment]
apologies again - in multitask overload including jumping around between different doc kvsched items. Meant to say diagram should be included in tutorials/kvs section of docs. Perhaps that one posted to slack week before last. https://github.com/ligato/docs/issues/20 should address this I guess.
