### ISSUE TITLE
Problem running Ligato 05_kv-scheduler tutorial

### ISSUE THREAD

**Issue by chrismetz09** [ligato/docs#40]
Problem below. Also how to tell if tutorial executed correctly or not.

$ go run main.go
main.go:21:2: cannot find package "github.com/ligato/cn-infra/agent" in any of:
	/usr/local/go/src/github.com/ligato/cn-infra/agent (from $GOROOT)
	/Users/chrismetz/go/src/github.com/ligato/cn-infra/agent (from $GOPATH)
main.go:22:2: cannot find package "github.com/ligato/cn-infra/infra" in any of:
	/usr/local/go/src/github.com/ligato/cn-infra/infra (from $GOROOT)
	/Users/chrismetz/go/src/github.com/ligato/cn-infra/infra (from $GOPATH)
main.go:23:2: cannot find package "github.com/ligato/cn-infra/logging" in any of:
	/usr/local/go/src/github.com/ligato/cn-infra/logging (from $GOROOT)
	/Users/chrismetz/go/src/github.com/ligato/cn-infra/logging (from $GOPATH)
main.go:24:2: cannot find package "github.com/ligato/vpp-agent/examples/tutorials/05_kv-scheduler/model" in any of:
	/usr/local/go/src/github.com/ligato/vpp-agent/examples/tutorials/05_kv-scheduler/model (from $GOROOT)
	/Users/chrismetz/go/src/github.com/ligato/vpp-agent/examples/tutorials/05_kv-scheduler/model (from $GOPATH)
main.go:25:2: cannot find package "github.com/ligato/vpp-agent/plugins/kvscheduler" in any of:
	/usr/local/go/src/github.com/ligato/vpp-agent/plugins/kvscheduler (from $GOROOT)
	/Users/chrismetz/go/src/github.com/ligato/vpp-agent/plugins/kvscheduler (from $GOPATH)
main.go:26:2: cannot find package "github.com/ligato/vpp-agent/plugins/kvscheduler/api" in any of:
	/usr/local/go/src/github.com/ligato/vpp-agent/plugins/kvscheduler/api (from $GOROOT)
	/Users/chrismetz/go/src/github.com/ligato/vpp-agent/plugins/kvscheduler/api (from $GOPATH)

**Comment by ondrej-fabry** [comment]
The import path should be `go.ligato.io/vpp-agent/v3/examples/tutorials/05_kv-scheduler/model`

**Comment by chrismetz09** [comment]
Got past that one.  Next received this:
$ go run main.go
# command-line-arguments
./main.go:73:44: undefined: NewIfDescriptor
./main.go:78:43: undefined: NewRouteDescriptor
