### ISSUE TITLE
Ligato REST Docs Update: #1786 and #1787

### ISSUE THREAD

**Issue by chrismetz09** [ligato/docs#97]
Update docs for:

https://github.com/ligato/vpp-agent/pull/1787

https://github.com/ligato/vpp-agent/pull/1786

**Comment by fgschwan** [comment]
Exported postman collection with usage examples of the new REST APIs: [examples.postman_collection.json.zip](https://github.com/ligato/docs/files/6116058/examples.postman_collection.json.zip)

**Comment by chrismetz09** [comment]
@fgschwan Tx for the postman. I can run new APIs for <NB Config> against quickstart setup. Attached is a very quick hack pdf to illustrate existing (../dump/..) and new (../configuration/..) REST API architecture. Is this roughly accurate?

[hack-lig-rest-api-pict.pdf](https://github.com/ligato/docs/files/6118348/hack-lig-rest-api-pict.pdf)

**Comment by fgschwan** [comment]
@chrismetz09 It is quite accurate. The only comment i have is to agentctl. Don't know why it sits between VPP-Agent and external KV store. Agentctl (for NB configuration handling) is basically a GRPC client. So it should be on the same level with REST client. It is just another way how to communicate with NB of VPP-Agent.

**Comment by chrismetz09** [comment]
@fgschwan, Filip, take a look at https://github.com/ligato/docs/pull/99. After this, I want to create new PR explaining NB vs SB, how agentctl vs rest fits, etc.

**Comment by fgschwan** [comment]
> 
> 
> @fgschwan, Filip, take a look at #99. After this, I want to create new PR explaining NB vs SB, how agentctl vs rest fits, etc.

@chrismetz09 looks good to me
